dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

before_script:
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8
  - mkdir build
  - cd build
  - cmake ..
script: make
